name: Publish spce-roi

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: spce-pdfreader-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build and publish
        run: |
          npm run build
          npm publish --access=public
